local_backend: true

backend:
  name: github
  repo: Nuclear-in-Space/nuclear-in-space.github.io
  branch: refactor/hugo-migration
  base_url: https://sveltia-cms-auth.nalin-gupta3142.workers.dev/callback

# i18n configuration: use separate root folders for each locale
i18n:
  structure: multiple_folders
  locales: [en, fr]
  default_locale: en

media_folder: "site/static/media"
public_folder: "/media"

collections:
  - name: main-pages
    label: Main Pages
    folder: "site/content"
    create: true
    delete: true
    i18n: true
    fields:
      - { label: Title, name: title, widget: string, i18n: true }
      - { label: Body, name: body, widget: markdown, i18n: true }
    index_file:
      i18n: true
      fields: # Fields for the index file
        - { name: title, label: Title, i18n: true }
        - { name: body, label: Body, widget: markdown, i18n: true }

  - name: conference-pages
    label: Conference Pages
    folder: "site/content"
    path: "conference/{{slug}}"
    create: true
    delete: true
    i18n: true
    fields:
      - { label: Title, name: title, widget: string, i18n: true }
      - { label: Body, name: body, widget: markdown, i18n: true }
    index_file:
      label: Conference Index
      i18n: true
      fields: # Fields for the index file
        - { name: title, label: Title, i18n: true }
        - { name: body, label: Body, widget: markdown, i18n: true }

  - name: library-pages
    label: Library Pages
    folder: "site/content"
    path: "library/{{slug}}"
    i18n: true
    fields:
      - { label: Title, name: title, widget: string, i18n: true }
      - { label: Body, name: body, widget: markdown, i18n: true }
    index_file:
      label: Library Index
      i18n: true
      fields: # Fields for the index file
        - { name: title, label: Title, i18n: true }
        - { name: body, label: Body, widget: markdown, i18n: true }
