backend:
  name: local
  repo: Nuclear-in-Space/nuclear-in-space.github.io

local_backend: true

# i18n configuration: use separate root folders for each locale
i18n:
  structure: multiple_root_folders
  locales: [en, fr]
  default_locale: en

media_folder: /static/media
public_folder: /media

collections:
  - name: main-pages
    label: Main pages
    folder: /content/{{locale}}
    filter: { field: lang, value: en }
    create: true
    delete: true
    nested:
      depth: 1
      summary: "{{title}}"
    filter:
      field: _type
      value: page
    fields:
      - { name: _type, widget: hidden, default: page }
      - { name: lang, label: Language, widget: select, options: [en, fr] }
      - { name: title, label: Title }
      - name: body
        label: Body
        widget: richtext
        buttons:
          [
            heading-two,
            heading-three,
            bold,
            italic,
            link,
            code,
            quote,
            bulleted-list,
            numbered-list
          ]
        editor_components:
          - image
          - shortcode
          - table
          - hr
    index_file:
      name: _index      # File name without a locale or extension. Default: _index
      label: Index File # Human-readable file label. Default: Index File
      icon: home        # Material Symbols icon name. Default: home
      fields:
        - { name: title, label: Title }
        - name: body
          label: Body
          widget: richtext
          buttons:
            [
              heading-two,
              heading-three,
              bold,
              italic,
              link,
              code,
              quote,
              bulleted-list,
              numbered-list
            ]
          editor_components:
            - image
            - shortcode
            - table
            - hr
      editor:
        preview: false # Hide the preview pane if needed. Default: true

  - name: conference
    label: Conference
    folder: content/{{locale}}/conference
    create: true
    delete: true
    filter:
      field: _type
      value: page
    nested:
      depth: 2
      summary: "{{title}}"
    fields:
      - { name: _type, widget: hidden, default: page }
      - { name: lang, label: Language, widget: select, options: [en, fr] }
      - { name: title, label: Title }
      - name: body
        label: Body
        widget: richtext
        buttons:
          [
            heading-two,
            heading-three,
            bold,
            italic,
            link,
            code,
            quote,
            bulleted-list,
            numbered-list
          ]
        editor_components:
          - image
          - shortcode
          - table
          - hr

    index_file:
      name: _index      # File name without a locale or extension. Default: _index
      label: Index File # Human-readable file label. Default: Index File
      icon: home        # Material Symbols icon name. Default: home
      fields:
        - { name: title, label: Title }
        - name: body
          label: Body
          widget: richtext
          buttons:
            [
              heading-two,
              heading-three,
              bold,
              italic,
              link,
              code,
              quote,
              bulleted-list,
              numbered-list
            ]
          editor_components:
            - image
            - shortcode
            - table
            - hr
      editor:
        preview: false # Hide the preview pane if needed. Default: true

  - name: library
    label: Library
    folder: content/{{locale}}/library
    # The library files are autogenerated so shouldn't be created or deleted.
    create: false
    delete: false
    slug: "{{slug}}"
    nested:
      depth: 2
      summary: "{{title}}"
    fields:
      - { name: title, label: Title }
      - name: slug
        label: Slug
        widget: string
        hint: "Used for the URL (no spaces)"
      - { name: date, label: Date, widget: datetime, required: false }
      - name: featured_image
        label: Featured Image
        widget: image
        required: false
      - name: body
        label: Body
        widget: richtext
        buttons:
          [
            bold,
            italic,
            link,
            code,
            quote,
            bulleted-list,
            numbered-list,
            heading-two,
            heading-three
          ]
        editor_components:
          - image
          - shortcode
          - table
          - hr

    index_file:
      name: _index
      label: Hub Index
      icon: article
      fields:
        - { name: title, label: Title }
        - { name: body, label: Body, widget: richtext }
