disabled = false
languageCode = "fr"
languageName = "Français"
weight = 1
title = "Nuclear Spaceflight"

[params]
  displayName = "Français"
  isoCode = "fr"
  rtl = false
  dateFormat = "2 janvier 2006"
  logo = "logo.png"
  copyright = "Droit d’auteur © 2025 SIGNuS"

["params.author"]
  name = "SIGNuS"
